export default {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        bg:          'var(--c-bg)',
        surface:     'var(--c-surface)',
        'surface-2': 'var(--c-surface-2)',
        border:      'var(--c-border)',
        'border-in': 'var(--c-border-in)',
        text:        'var(--c-text)',
        'text-2':    'var(--c-text-2)',
        'text-secondary': 'var(--c-text-sec)',
        muted:       'var(--c-text-muted)',
        'text-faint':  'var(--c-text-faint)',
        accent:      'var(--c-accent)',
        'accent-bg': 'var(--c-accent-bg)',
        'accent-bdr': 'var(--c-accent-bdr)',
        'accent-text': 'var(--c-accent-txt)',
        success:     'var(--c-success)',
        'success-bg': 'var(--c-success-bg)',
        danger:      'var(--c-danger)',
        'danger-bg': 'var(--c-danger-bg)',
        warning:     '#D97706',
        'warning-bg': '#FFFBEB',
        // Static palette for gradients and fixed accents
        primary:   '#6366F1',
        secondary: '#8B5CF6',
        tertiary:  '#EC4899',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '10px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '28px',
      },
      boxShadow: {
        xs:   '0 1px 2px rgba(0, 0, 0, 0.03)',
        sm:   '0 1px 3px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)',
        DEFAULT: '0 1px 3px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.03)',
        md:   '0 4px 6px rgba(0, 0, 0, 0.05), 0 1px 3px rgba(0, 0, 0, 0.06)',
        lg:   '0 8px 16px rgba(0, 0, 0, 0.06), 0 4px 6px rgba(0, 0, 0, 0.04)',
        xl:   '0 12px 24px rgba(0, 0, 0, 0.06)',
      },
      animation: {
        'fade-in': 'fadeIn 0.25s ease-out',
        'slide-up': 'slideUp 0.25s ease-out',
        'blink': 'blink 1s step-end infinite',
        'pulse-dot': 'pulseDot 2s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s infinite',
      },
      keyframes: {
        fadeIn:  { from: { opacity: 0 }, to: { opacity: 1 } },
        slideUp: { from: { opacity: 0, transform: 'translateY(6px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        blink:   { '0%,100%': { opacity: 1 }, '50%': { opacity: 0 } },
        pulseDot: { '0%,100%': { transform: 'scale(1)', opacity: 1 }, '50%': { transform: 'scale(1.2)', opacity: 0.6 } },
        shimmer: { '0%': { backgroundPosition: '-300px 0' }, '100%': { backgroundPosition: '300px 0' } },
      },
      transitionProperty: {
        'colors': 'color, background-color, border-color, text-decoration-color, fill, stroke',
      },
    },
  },
  plugins: [],
}
